version: 2.1
jobs:
  build-rocky8:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - run:
          name: Build Docker image
          command: ./build.sh 8

  build-rocky9:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - run:
          name: Build Docker image
          command: ./build.sh 9

  build-rocky10:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - run:
          name: Build Docker image
          command: ./build.sh 10

workflows:
  version: 2.1
  build-test:
    jobs:
      - build-rocky8
      - build-rocky9
      - build-rocky10
