version: 2.1
jobs:
  build-rhel7:
    docker:
      - image: rockylinux:9
    steps:
      - checkout
      - run:
          name: Install build dependencies
          command: |
             sudo dnf install podman-docker
      - run:
          name: Build Docker image
          command: ./build.sh 7

  build-rhel8:
    docker:
      - image: rockylinux:9
    steps:
      - checkout
      - run:
          name: Install build dependencies
          command: |
             sudo dnf install podman-docker
      - run:
          name: Build Docker image
          command: ./build.sh 8

  build-rhel9:
    docker:
      - image: rockylinux:9
    steps:
      - checkout
      - run:
          name: Install build dependencies
          command: |
             sudo dnf install podman-docker
      - run:
          name: Build Docker image
          command: ./build.sh 8

workflows:
  version: 2.1
  build-test:
    jobs:
      - build-rhel7
      - build-rhel8
      - build-rhel9
